version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:30"
    timezone: Asia/Kolkata
  open-pull-requests-limit: 10

- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "08:30"
    timezone: Asia/Kolkata
  open-pull-requests-limit: 10
