import sys
platform = sys.platform
cmd = 'logic'

cmd += './'
LANGS = [{'req': 'gcc',
		  'commandL': cmd,
		  'commandW': 'logic',
		  'link': 'https://gcc.gnu.org/install/',
		  'compileL': 'gcc -o logic logic.c',
		  'compileW': 'gcc logic.c -o logic'},
		 {'req': 'g++',
		  'commandL': cmd,
		  'commandW': 'logic',
		  'link': 'https://www.cs.odu.edu/~zeil/cs250PreTest/latest/Public/installingACompiler/',
		  'compileL': 'g++ -o logic logic.cpp',
		  'compileW': 'g++ logic.cpp -o logic'},
		 {'req': 'Java',
		  'commandL': 'java logic',
		  'commandW': 'java logic',
		  'link': 'https://introcs.cs.princeton.edu/java/15inout/windows-cmd.html',
		  'compileL': 'javac logic.java',
		  'compileW': 'javac logic.java'},
		 {'req': 'Python',
		  'commandL': 'python tc_generator/logic.py',
		  'commandW': 'python tc_generator/logic.py',
		  'link': 'https://www.python.org/downloads/',
		  'compileL': '',
		  'compileW': ''},
		 {'req': 'C#',
		  'commandL': 'mono logic',
		  'commandW': 'mono logic.exe',
		  'link': 'https://www.mono-project.com/docs/about-mono/languages/csharp/',
		  'compileL': 'msc logic.cs',
		  'compileW': 'csc logic.cs'},
		 {'req': 'Golang',
		  'commandL': cmd,
		  'commandW': 'logic',
		  'link': 'https://golang.org/doc/install',
		  'compileL': 'go build logic.go',
		  'compileW': 'go build logic.go'},
		 ]
