LANGS = [{'req': 'gcc',
          'command': './logic',
          'link': 'https://gcc.gnu.org/install/',
          'compile': 'gcc -o logic logic.c'},
         {'req': 'g++',
          'command': './logic',
          'link': 'https://www.cs.odu.edu/~zeil/cs250PreTest/latest/Public/installingACompiler/',
          'compile': 'g++ -o logic logic.cpp'},
         {'req': 'Java',
          'command': 'java logic',
          'link': 'https://introcs.cs.princeton.edu/java/15inout/windows-cmd.html',
          'compile': 'javac logic.java'},
         {'req': 'Python',
          'command': 'python logic.py',
          'link': 'https://www.python.org/downloads/',
          'compile': ''},
         {'req': 'C#',
          'command': 'mono logic',
          'link': 'https://www.mono-project.com/docs/about-mono/languages/csharp/',
          'compile': 'msc logic.cs'},
         {'req': 'Golang',
          'command': './logic',
          'link': 'https://golang.org/doc/install',
          'compile': 'go build logic.go'},
         ]
